In [1]:
import pandas as pd

In [4]:
filename = 'abalone.data'

In [5]:
df = pd.DataFrame()

In [10]:
names = [ 'Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']

In [34]:
df_small = pd.read_csv(filename ,names = names, delimiter=',').sample(20)
df_small

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
3721   M   0.430     0.310   0.130        0.6485          0.2735   
1133   M   0.570     0.460   0.150        1.0375          0.5415   
927    I   0.435     0.325   0.120        0.3995          0.1815   
2626   I   0.220     0.160   0.050        0.0490          0.0215   
2059   I   0.490     0.370   0.110        0.5380          0.2710   
2708   M   0.735     0.570   0.175        1.8800          0.9095   
2608   F   0.625     0.490   0.175        1.1075          0.4485   
561    I   0.515     0.400   0.120        0.6590          0.2705   
1818   F   0.695     0.550   0.185        1.6790          0.8050   
3429   I   0.280     0.210   0.065        0.1110          0.0425   
3427   M   0.740     0.605   0.200        2.4925          1.1455   
2285   I   0.420     0.330   0.100        0.3520          0.1635   
2570   I   0.465     0.355   0.110        0.4740          0.2300   
2227   I   0.275     0.200   0.075        0.0860          0.0305   
3357   I   0.375     0.285   0.100        0.2390          0.1050   
368    M   0.630     0.490   0.180        1.1300          0.4580   
1881   I   0.550     0.450   0.130        0.8040          0.3375   
367    F   0.580     0.455   0.120        1.0735          0.4790   
3892   F   0.500     0.400   0.150        0.8085          0.2730   
1629   I   0.570     0.430   0.145        0.8330          0.3540   

      Viscera weight  Shell weight  Rings  
3721          0.1630        0.1840      9  
1133          0.2035        0.2500      9  
927           0.0610        0.1125      8  
2626          0.0100        0.0150      4  
2059          0.1035        0.1390      8  
2708          0.3870        0.4880     11  
2608          0.2165        0.3595      8  
561           0.1790        0.1700     13  
1818          0.4015        0.3965     10  
3429          0.0285        0.0300      6  
3427          0.5750        0.5235     13  
2285          0.0890        0.1000      9  
2570          0.1005        0.1200      7  
2227          0.0190        0.0300      7  
3357          0.0555        0.0700      8  
368           0.2765        0.3150     12  
1881          0.1405        0.2300      6  
367           0.2735        0.2650     10  
3892          0.1120        0.2950     13  
1629          0.1440        0.2815     10

In [35]:
replace_list = {"Sex" : {"M": 0, "F" : 1, "I": 2}}
df_small.replace(replace_list,inplace=True)

In [13]:
df = pd.read_csv(filename ,names = names, delimiter=',')
del df['Rings']

In [14]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  
0         0.150  
1         0.070  
2         0.210  
3         0.155  
4         0.055

In [15]:
replace_list = {"Sex" : {"M": 0, "F" : 1, "I": 2}}
df.replace(replace_list,inplace=True)

In [16]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    0   0.455     0.365   0.095        0.5140          0.2245   
1    0   0.350     0.265   0.090        0.2255          0.0995   
2    1   0.530     0.420   0.135        0.6770          0.2565   
3    0   0.440     0.365   0.125        0.5160          0.2155   
4    2   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  
0          0.1010         0.150  
1          0.0485         0.070  
2          0.1415         0.210  
3          0.1140         0.155  
4          0.0395         0.055

In [18]:
from sklearn import cluster, datasets, mixture

In [23]:
g = mixture.GaussianMixture(n_components=12)

In [26]:
x = df.iloc[:,:8].values

In [27]:
g.fit(x)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=12, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [32]:
g.predict(x)[0]

10

In [33]:
g.predict_proba(x)[563]

array([2.56960161e-04, 0.00000000e+00, 0.00000000e+00, 8.16817880e-03,
       0.00000000e+00, 0.00000000e+00, 9.91574861e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [40]:
clusters_small = g.predict_proba(df_small.iloc[:,:8])
rings_small = df_small['Rings']

In [29]:
g.score(x)

19.727429831163363

In [42]:
clusters_small[2]

array([0.00000000e+00, 0.00000000e+00, 5.60755581e-10, 0.00000000e+00,
       5.53411343e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.94465886e-01])

In [58]:
pd.get_dummies(rings_small).head()

4   6   7   8   9   10  11  12  13
3721   0   0   0   0   1   0   0   0   0
1133   0   0   0   0   1   0   0   0   0
927    0   0   0   1   0   0   0   0   0
2626   1   0   0   0   0   0   0   0   0
2059   0   0   0   1   0   0   0   0   0

In [69]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [71]:
cluster_age = clusters_small.T @ pd.get_dummies(rings_small)
cluster_age = cluster_age / cluster_age.sum(1)[:,None]
cluster_age

array([[0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.103, 0.   , 0.   , 0.897, 0.   ],
       [0.251, 0.251, 0.251, 0.246, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.019, 0.   , 0.247, 0.   , 0.   , 0.735],
       [0.   , 0.615, 0.   , 0.004, 0.001, 0.26 , 0.   , 0.   , 0.119],
       [0.   , 0.   , 0.   , 0.   , 0.397, 0.   , 0.405, 0.197, 0.   ],
       [0.   , 0.   , 0.   , 0.353, 0.   , 0.613, 0.   , 0.   , 0.033],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.008, 0.006, 0.986],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.645, 0.   , 0.016, 0.002, 0.337],
       [0.   , 0.   , 0.   , 0.   , 0.682, 0.   , 0.   , 0.318, 0.   ],
       [0.   , 0.   , 0.185, 0.373, 0.185, 0.107, 0.   , 0.   , 0.149]])

In [79]:
predicted_classes = g.predict_proba(x) @ cluster_age
predicted_classes[:3]

array([[0.   , 0.   , 0.   , 0.   , 0.653, 0.   , 0.   , 0.347, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.352, 0.   , 0.612, 0.   , 0.   , 0.036]])

In [80]:
age_labels = np.array(pd.get_dummies(rings_small).columns)
age_labels

array([ 4,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int64)

In [81]:
predicted_age = predicted_classes @ age_labels
predicted_age.shape

(4177,)

In [82]:
predicted_age[:5]

array([10.04 ,  9.001,  9.404,  9.974,  6.243])